development:
  adapter: postgresql
  encoding: unicode 
  host: localhost
  database: photouploadapi_development 
  pool: 5
  username: neilmarion
  password: root

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: photouploadapi_test
  pool: 5
  username: neilmarion 
  password: root 

